default: true
ktor:
  application:
    modules:
      - me.anlear.ApplicationKt.module
  deployment:
    # YOUR SERVER PORT
    port: 80
app:
  # URL, куда будут приходить запросы от Telegram
  url: "YOUR_URL"
  # Раз в сколько часов будет происходить обновление секретного токена
  secretLifetime: 4
  telegram:
    botToken: "YOUR_BOT_TOKEN_HERE"
  database:
    url: "YOUR_DATABASE_URL"
    user: "YOUR_DATABASE_USER"
    password: "YOUR_DATABASE_PASSWORD"