default: true
ktor:
  application:
    modules:
      - me.anlear.ApplicationKt.module
  deployment:
    # YOUR SERVER PORT
    port: 80
jwt:
  domain: "YOUR_DOMAIN"
  audience: "YOUR_AUDIENCE"
  realm: "YOUR_REALM"
  secret: "YOUR_SECRET"
app:
  telegram:
    botToken: "YOUR_BOT_TOKEN_HERE"
  database:
    url: "YOUR_URL"
    user: "YOUR_USER"
    password: "YOUR_PASSWORD"